# Generated by Django 3.2.9 on 2021-11-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_auto_20211116_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
